In [2]:
import numpy as np

### User Inputs and Number of Neurons

In [33]:
# # Number of hidden neurons
# neurons = int(input("Enter number of neurons in hidden layer: "))

# # Number of training samples
# inp = int(input("Enter the inputs: "))

# # Number of features
# features = int(input("Enter number of input features: "))


# print("\nEnter input matrix row by row:")

# inputs = []
# for i in range(samples):
#     row = list(map(float, input().split()))
#     inputs.append(row)

# X = np.array(inputs)


# print("\nEnter correct outputs:")

# outputs = []
# for i in range(samples):
#     val = float(input())
#     outputs.append([val])

# Y = np.array(outputs)

In [23]:
inputs = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
outputs= np.array([[0], [1], [1], [0]])
print(inputs, "\n\n", outputs, "\n")

weights_to_hidden = np.random.rand(2, 2)
print(weights_to_hidden, "\n")
weights_to_output = np.random.rand(1, 2)
print(weights_to_output)

learning_rate = 0.1

[[0 0]
 [0 1]
 [1 0]
 [1 1]] 

 [[0]
 [1]
 [1]
 [0]] 

[[0.65911598 0.51310917]
 [0.49667321 0.11705182]] 

[[0.90832598 0.69636687]]


In [30]:
def sigmoid(x):
    return (1 / (1 + np.exp(-x)))

def error(y_true, y_pred):
    mse = np.mean((y_true - y_pred) ** 2)
    return mse


### Forward propogation

In [32]:
hiddenLayer_input = np.dot(weights, inputs[0])
print(hidden_input)

hidden_input_T = hidden_input.reshape(-1,1)
hidden_output = sigmoid(hidden_input_T)
print(hidden_output)

input_to_outputLayer = np.dot(weights_to_output, hidden_output)
print("\n", input_to_outputLayer)

outputLayer_output = sigmoid(input_to_outputLayer)
print(outputLayer_output)

error_cal = error(outputs[0], outputLayer_output)
print(error_cal)

[0. 0.]
[[0.5]
 [0.5]]

 [[0.80234642]]
[[0.69047618]]
0.4767573555233369


### Back Propogation of error

In [36]:
partialDerivation = error_cal * (outputLayer_output*(1-outputLayer_output))
print(partialDerivation)

change_in_weights = partialDerivation * hidden_output
print(change_in_weights)

[[0.10189202]]
[[0.05094601]
 [0.05094601]]
